using GraduationProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraduationProject.Configurations.EntityTypeConfigurations
{
    public class IssueEntityTypeConfiguration:IEntityTypeConfiguration<Issue>
    {
        public void Configure(EntityTypeBuilder<Issue> builder)
        {

            //Relationship
            builder.HasOne(a => a.RespondingAdmin)
                .WithMany(i => i.Issues)
                .HasForeignKey(i => i.AdminId);

            //Id
            builder.HasKey(b => b.Id);

            builder.Property(b => b.Id)
                .ValueGeneratedOnAdd();


            //SubmitDate
            builder.Property(b => b.SubmitDate)
                .HasDefaultValueSql("GETDATE()");


            //RespondDate
            builder.Property(b => b.RespondDate)
                .IsRequired(false);

            //Status
            builder.Property(b => b.Status)
                .HasConversion(new EnumToStringConverter<IssueStatus>());

            builder.Property(b => b.Status)
                .HasColumnType("varchar(15)");

            builder.Property(b => b.Status)
                .HasDefaultValue(IssueStatus.Submitted);

            //Description
            builder.Property(b => b.Description)
                 .IsRequired(true);

            //Response
            builder.Property(b => b.Response)
                 .IsRequired(false);

            //AdminId
            builder.Property(b => b.AdminId)
                .IsRequired(false);

        }
    }
}


//Specifications:
/*
    Id:
        - key
        - autoGenerated
    Description:
        - required
    Response:
        - not required
    SubmitDate:
        - setCurrentDatebydefault
    RespondDate:
        - not required
    
    Status:
        - defaultValue=>Submitted
        - written into database as string
        - string with max 15 characters

    AdminId
        - not required
 
    Check Entity for Foreign key restore navigation property?

 */
